//! Tool-call parsers.
//!
//! Ported from every concrete parser in `mlx-lm`'s `mlx_lm/tool_parsers/`
//! (`json_tools`, `pythonic`, `mistral`, `qwen3_coder`, `glm47`, `kimi_k2`,
//! `longcat`, `minimax_m2`, `function_gemma`, `gemma4`) plus the
//! `_infer_tool_parser` selector in `mlx_lm/tokenizer_utils.py` (~548+).
//! Cross-referenced against `mlx-swift-lm`'s `MLXLMCommon/Tool/*`
//! (`ToolCall`, `ToolCallFormat`, `ToolCallProcessor`, `Value`, `Parsers`)
//! for the abstraction shape: a `ToolParser` trait producing structured
//! `ToolCall`s, selected by chat-template content.
//!
//! Python `ast.literal_eval` is approximated with a JSON-first parse and a
//! conservative Python-literal fallback (`True`/`False`/`None`, single-quoted
//! strings); values that fail both are kept as the original string, matching
//! the Python parsers' "keep as string" behavior.

use serde_json::Value;

use crate::Error;

// Constant marker + ordered selection dispatch table, regenerated by
// `cargo xtask-codegen` from `mlxrs/data/tokenizer/tool_parsers.toml`
// (single source of truth; mlx-lm df1d3f3) into the committed
// `crate::tokenizer::generated` module. Parser *logic* below stays Rust and
// consumes this table instead of inline string literals.
use crate::tokenizer::generated::{TOOL_PARSER_MARKERS, TOOL_PARSER_SELECT};

/// `tool_call_start` for `name` from the generated table.
fn marker_start(name: &str) -> &'static str {
  TOOL_PARSER_MARKERS
    .iter()
    .find(|m| m.name == name)
    .map(|m| m.start)
    .unwrap_or("")
}

/// `tool_call_end` for `name` from the generated table.
fn marker_end(name: &str) -> &'static str {
  TOOL_PARSER_MARKERS
    .iter()
    .find(|m| m.name == name)
    .map(|m| m.end)
    .unwrap_or("")
}

/// A single parsed tool call (Swift `ToolCall` shape: name + arguments,
/// optional id for kimi-style calls).
#[derive(Debug, Clone, PartialEq)]
pub struct ToolCall {
  /// Function name.
  pub name: String,
  /// Arguments as a JSON object (or other JSON value for raw payloads).
  pub arguments: Value,
  /// Optional tool-call id (kimi_k2 emits `functions.name:idx`).
  pub id: Option<String>,
}

impl ToolCall {
  fn new(name: impl Into<String>, arguments: Value) -> Self {
    Self {
      name: name.into(),
      arguments,
      id: None,
    }
  }
}

/// A tool-call parser (Python `tool_module.parse_tool_call`). Implementors
/// also expose the `tool_call_start` / `tool_call_end` delimiters.
pub trait ToolParser: Send + Sync {
  /// Parse one assistant tool-call payload into one or more [`ToolCall`]s.
  fn parse(&self, text: &str, tools: Option<&Value>) -> Result<Vec<ToolCall>, Error>;

  /// The stable parser name (matches the Python module name).
  fn name(&self) -> &'static str;

  /// The `tool_call_start` delimiter, looked up from the marker table
  /// regenerated by `cargo xtask-codegen` from
  /// `mlxrs/data/tokenizer/tool_parsers.toml` into the committed
  /// `mlxrs/src/tokenizer/generated.rs`.
  fn tool_call_start(&self) -> &'static str {
    marker_start(self.name())
  }

  /// The `tool_call_end` delimiter, from the generated marker table.
  fn tool_call_end(&self) -> &'static str {
    marker_end(self.name())
  }

  /// Whether a *tagged* call's payload (the text between `tool_call_start` and
  /// `tool_call_end`) is exactly one top-level JSON object.
  ///
  /// Default `false`. When `true`, the streaming [`ToolCallProcessor`] locates
  /// the end tag with a JSON-string-aware balanced-object scan rather than a
  /// naive substring search, so an end-delimiter that occurs *inside* a JSON
  /// string argument value (e.g. `{"s":"</tool_call>"}`) is not mistaken for
  /// the real closing tag and the call is not corrupted (Codex round-2
  /// finding 2). Only formats whose payload is unambiguously a single JSON
  /// object may opt in; structured/XML payloads (`qwen3_coder`, `glm47`,
  /// `longcat`, `minimax_m2`, `kimi_k2`, the `gemma` family, `pythonic`) keep
  /// the simple substring detection.
  fn tagged_payload_is_json(&self) -> bool {
    false
  }
}

fn err(msg: impl Into<String>) -> Error {
  Error::tokenizer(msg.into())
}

/// Approximates Python `ast.literal_eval` enough for tool-arg coercion:
/// JSON first, then `True`/`False`/`None`, single-quoted strings, and bare
/// ints/floats. Falls back to returning the input as a JSON string.
fn literal_eval(s: &str) -> Value {
  let t = s.trim();
  if let Ok(v) = serde_json::from_str::<Value>(t) {
    return v;
  }
  match t {
    "True" | "true" => return Value::Bool(true),
    "False" | "false" => return Value::Bool(false),
    "None" | "null" => return Value::Null,
    _ => {}
  }
  if (t.starts_with('\'') && t.ends_with('\'') && t.len() >= 2)
    || (t.starts_with('"') && t.ends_with('"') && t.len() >= 2)
  {
    return Value::String(t[1..t.len() - 1].to_owned());
  }
  if let Ok(i) = t.parse::<i64>() {
    return Value::Number(i.into());
  }
  if let Ok(f) = t.parse::<f64>()
    && let Some(n) = serde_json::Number::from_f64(f)
  {
    return Value::Number(n);
  }
  // Python-list/tuple/dict-ish: try swapping single quotes to double quotes.
  if (t.starts_with('[') && t.ends_with(']'))
    || (t.starts_with('{') && t.ends_with('}'))
    || (t.starts_with('(') && t.ends_with(')'))
  {
    let swapped = t
      .replace('\'', "\"")
      .replace("(", "[")
      .replace(")", "]")
      .replace("True", "true")
      .replace("False", "false")
      .replace("None", "null");
    if let Ok(v) = serde_json::from_str::<Value>(&swapped) {
      return v;
    }
  }
  Value::String(t.to_owned())
}

/// JSON-then-literal deserialize (Python `_deserialize` in glm47/longcat/kimi).
fn deserialize(value: &str) -> Value {
  if let Ok(v) = serde_json::from_str::<Value>(value) {
    return v;
  }
  literal_eval(value)
}

fn obj(name: &str, args: Value) -> Vec<ToolCall> {
  vec![ToolCall::new(name, args)]
}

fn tool_properties<'a>(
  tools: Option<&'a Value>,
  func_name: &str,
) -> Option<&'a serde_json::Map<String, Value>> {
  let arr = tools?.as_array()?;
  for tool in arr {
    let f = tool.get("function")?;
    if f.get("name").and_then(Value::as_str) == Some(func_name) {
      return f
        .get("parameters")
        .and_then(|p| p.get("properties"))
        .and_then(Value::as_object);
    }
  }
  None
}

fn string_arg_names(tools: Option<&Value>, func_name: &str) -> Vec<String> {
  tool_properties(tools, func_name)
    .map(|props| {
      props
        .iter()
        .filter(|(_, v)| v.get("type").and_then(Value::as_str) == Some("string"))
        .map(|(k, _)| k.clone())
        .collect()
    })
    .unwrap_or_default()
}

// ----------------------------------------------------------------------------
// json_tools
// ----------------------------------------------------------------------------

/// `json_tools` — `<tool_call>{json}</tool_call>`; the payload is plain JSON.
pub struct JsonTools;

impl ToolParser for JsonTools {
  fn parse(&self, text: &str, _tools: Option<&Value>) -> Result<Vec<ToolCall>, Error> {
    let v: Value =
      serde_json::from_str(text.trim()).map_err(|e| err(format!("json_tools: {e}")))?;
    let name = v
      .get("name")
      .and_then(Value::as_str)
      .ok_or_else(|| err("json_tools: missing name"))?;
    let args = v.get("arguments").cloned().unwrap_or(Value::Null);
    Ok(obj(name, args))
  }
  fn name(&self) -> &'static str {
    "json_tools"
  }
  /// `json_tools`' tagged payload is exactly `{json}`, so the end tag is
  /// located with the JSON-aware balanced-object scan.
  fn tagged_payload_is_json(&self) -> bool {
    true
  }
}

// ----------------------------------------------------------------------------
// pythonic: [func(arg="v", n=2)]
// ----------------------------------------------------------------------------

/// `pythonic` — `<|tool_call_start|>[name(a="x", b=2)]<|tool_call_end|>`.
pub struct Pythonic;

impl ToolParser for Pythonic {
  fn parse(&self, text: &str, _tools: Option<&Value>) -> Result<Vec<ToolCall>, Error> {
    // _tool_call_regex = \[(\w+)\((.*?)\)\]
    let (fname, args_str) =
      find_pythonic_call(text).ok_or_else(|| err("pythonic: No function provided."))?;
    let mut arguments = serde_json::Map::new();
    for (k, v) in parse_kw_args(&args_str)? {
      arguments.insert(k, literal_eval(&v));
    }
    Ok(obj(&fname, Value::Object(arguments)))
  }
  fn name(&self) -> &'static str {
    "pythonic"
  }
}

fn find_pythonic_call(text: &str) -> Option<(String, String)> {
  // Equivalent of \[(\w+)\((.*?)\)\] with DOTALL, first match.
  let bytes = text.as_bytes();
  let mut i = 0;
  while i < bytes.len() {
    if bytes[i] == b'[' {
      let mut j = i + 1;
      let name_start = j;
      while j < bytes.len() && (bytes[j].is_ascii_alphanumeric() || bytes[j] == b'_') {
        j += 1;
      }
      if j > name_start && j < bytes.len() && bytes[j] == b'(' {
        let name = text[name_start..j].to_owned();
        // non-greedy up to `)]`
        let rest = &text[j + 1..];
        if let Some(close) = rest.find(")]") {
          return Some((name, rest[..close].to_owned()));
        }
      }
    }
    i += 1;
  }
  None
}

/// Parse `key=value, key="value"` pairs (Python `_tool_args_regex`
/// `(\w+)=(?:"([^"]*)"|([^,]+))(?:,\s*|$)`, `findall`).
///
/// All slicing is on offsets measured against the *original* `rest` slice
/// (the leading-whitespace skip is folded into the cursor), so a non-ASCII
/// value after spaces (`city=  "é"`) can never slice a UTF-8 char boundary.
/// Malformed input returns a tokenizer parse [`Error`] rather than panicking.
fn parse_kw_args(s: &str) -> Result<Vec<(String, String)>, Error> {
  let mut out = Vec::new();
  let mut rest = s.trim();
  while !rest.is_empty() {
    let eq = match rest.find('=') {
      Some(e) => e,
      None => break,
    };
    // `rest[..eq]` ends just before an ASCII `=`, always a char boundary.
    let key = rest[..eq].trim().to_owned();
    // Absolute byte offset of the value start within `rest`, after the `=`
    // and any whitespace. `eq + 1` is past the 1-byte `=` (char boundary);
    // the trimmed prefix length is added back so every later index into
    // `rest` is computed from `rest` itself, never from a re-sliced `after`.
    let val_start = {
      let after = &rest[eq + 1..];
      eq + 1 + (after.len() - after.trim_start().len())
    };
    let value_region = &rest[val_start..];
    let (val, consumed) = if let Some(stripped) = value_region.strip_prefix('"') {
      // Quoted: `"([^"]*)"` — inner up to the next `"`.
      match stripped.find('"') {
        // val_start + 1 (open quote) + end (inner len) + 1 (close quote).
        Some(end) => (stripped[..end].to_owned(), val_start + 1 + end + 1),
        // Unterminated quote: keep the rest as the value (matches the prior
        // lenient behaviour) and stop — no further char-boundary slicing.
        None => (stripped.to_owned(), rest.len()),
      }
    } else {
      // Unquoted: `[^,]+` — up to the next `,` (or end).
      let end = value_region.find(',').unwrap_or(value_region.len());
      (value_region[..end].trim().to_owned(), val_start + end)
    };
    out.push((key, val));
    if consumed >= rest.len() {
      break;
    }
    // `consumed` is always a char boundary: it is `val_start` (boundary)
    // plus byte lengths of whole matched ASCII-delimited regions. Guard
    // anyway so corrupt offsets surface as an `Error`, never a panic.
    if !rest.is_char_boundary(consumed) {
      return Err(err("pythonic: malformed argument encoding"));
    }
    rest = rest[consumed..]
      .trim_start()
      .trim_start_matches(',')
      .trim_start();
  }
  Ok(out)
}

// ----------------------------------------------------------------------------
// mistral: name[ARGS]{json}
// ----------------------------------------------------------------------------

/// `mistral` — `[TOOL_CALLS]name[ARGS]{json}`.
pub struct Mistral;

impl ToolParser for Mistral {
  fn parse(&self, text: &str, _tools: Option<&Value>) -> Result<Vec<ToolCall>, Error> {
    // \s*(\w+)\[ARGS\]\s*(\{.*\})
    let idx = text
      .find("[ARGS]")
      .ok_or_else(|| err(format!("mistral: Could not parse tool call from: {text}")))?;
    let name = text[..idx].trim().to_owned();
    let after = text[idx + "[ARGS]".len()..].trim_start();
    let brace = after
      .find('{')
      .ok_or_else(|| err("mistral: no json args"))?;
    let json_str = after[brace..].trim_end();
    let args: Value = serde_json::from_str(json_str).map_err(|e| err(format!("mistral: {e}")))?;
    Ok(obj(&name, args))
  }
  fn name(&self) -> &'static str {
    "mistral"
  }
}

// ----------------------------------------------------------------------------
// qwen3_coder: <function=name>...<parameter=p>v</parameter></function>
// ----------------------------------------------------------------------------

/// `qwen3_coder` — XML-style `<function=name><parameter=p>v</parameter></function>`.
pub struct Qwen3Coder;

impl ToolParser for Qwen3Coder {
  fn parse(&self, text: &str, tools: Option<&Value>) -> Result<Vec<ToolCall>, Error> {
    // _function_regex = <function=(.*?)</function>$ (DOTALL, findall->[0])
    let start = text
      .find("<function=")
      .ok_or_else(|| err("qwen3_coder: No function provided."))?;
    let after = &text[start + "<function=".len()..];
    let end = after
      .rfind("</function>")
      .ok_or_else(|| err("qwen3_coder: No function provided."))?;
    let body = &after[..end];
    let gt = body
      .find('>')
      .ok_or_else(|| err("qwen3_coder: malformed function"))?;
    let func_name = body[..gt].to_owned();
    let params_str = &body[gt + 1..];
    let props = tool_properties(tools, &func_name);
    let mut args = serde_json::Map::new();
    for cap in find_all(params_str, "<parameter=", "</parameter>") {
      let pgt = match cap.find('>') {
        Some(p) => p,
        None => continue,
      };
      let pname = cap[..pgt].to_owned();
      let mut pval = cap[pgt + 1..].to_owned();
      if let Some(r) = pval.strip_prefix('\n') {
        pval = r.to_owned();
      }
      if let Some(r) = pval.strip_suffix('\n') {
        pval = r.to_owned();
      }
      args.insert(pname.clone(), convert_param_value(&pval, &pname, props));
    }
    Ok(obj(&func_name, Value::Object(args)))
  }
  fn name(&self) -> &'static str {
    "qwen3_coder"
  }
}

fn convert_param_value(
  v: &str,
  name: &str,
  props: Option<&serde_json::Map<String, Value>>,
) -> Value {
  if v.eq_ignore_ascii_case("null") {
    return Value::Null;
  }
  let Some(props) = props else {
    return Value::String(v.to_owned());
  };
  let Some(schema) = props.get(name) else {
    return Value::String(v.to_owned());
  };
  let ptype = schema
    .get("type")
    .and_then(Value::as_str)
    .unwrap_or("string")
    .trim()
    .to_lowercase();
  const STR: &[&str] = &["string", "str", "text", "varchar", "char", "enum"];
  const BOOL: &[&str] = &["boolean", "bool", "binary"];
  const OBJ: &[&str] = &["object", "array", "arr"];
  if STR.contains(&ptype.as_str()) {
    Value::String(v.to_owned())
  } else if ["int", "uint", "long", "short", "unsigned"]
    .iter()
    .any(|p| ptype.starts_with(p))
  {
    v.trim()
      .parse::<i64>()
      .map(|i| Value::Number(i.into()))
      .unwrap_or_else(|_| Value::String(v.to_owned()))
  } else if ptype.starts_with("num") || ptype.starts_with("float") {
    match v.trim().parse::<f64>() {
      Ok(f) if f.fract() == 0.0 => Value::Number((f as i64).into()),
      Ok(f) => serde_json::Number::from_f64(f)
        .map(Value::Number)
        .unwrap_or(Value::Null),
      Err(_) => Value::String(v.to_owned()),
    }
  } else if BOOL.contains(&ptype.as_str()) {
    Value::Bool(v.trim().eq_ignore_ascii_case("true"))
  } else if OBJ.contains(&ptype.as_str()) || ptype.starts_with("dict") || ptype.starts_with("list")
  {
    serde_json::from_str(v).unwrap_or_else(|_| literal_eval(v))
  } else {
    literal_eval(v)
  }
}

/// Find all substrings between `open` and the next `close` (DOTALL,
/// non-greedy), returning the inner text of each match.
fn find_all(text: &str, open: &str, close: &str) -> Vec<String> {
  let mut out = Vec::new();
  let mut i = 0;
  while let Some(s) = text[i..].find(open) {
    let abs = i + s + open.len();
    if let Some(e) = text[abs..].find(close) {
      out.push(text[abs..abs + e].to_owned());
      i = abs + e + close.len();
    } else {
      break;
    }
  }
  out
}

// ----------------------------------------------------------------------------
// glm47: name<arg_key>k</arg_key><arg_value>v</arg_value>...
// ----------------------------------------------------------------------------

/// `glm47` — `name<arg_key>k</arg_key><arg_value>v</arg_value>` with JSON /
/// plain-text fallbacks.
pub struct Glm47;

impl ToolParser for Glm47 {
  fn parse(&self, text: &str, tools: Option<&Value>) -> Result<Vec<ToolCall>, Error> {
    if let Some(idx) = text.find("<arg_key>") {
      let func_name = text[..idx].trim().to_owned();
      let string_args = string_arg_names(tools, &func_name);
      let mut args = serde_json::Map::new();
      for (k, v) in find_kv_pairs(
        text,
        "<arg_key>",
        "</arg_key>",
        "<arg_value>",
        "</arg_value>",
      ) {
        let key = k.trim().to_owned();
        let val = if string_args.contains(&key) {
          Value::String(v.trim().to_owned())
        } else {
          deserialize(v.trim())
        };
        args.insert(key, val);
      }
      return Ok(obj(&func_name, Value::Object(args)));
    }
    // Fallbacks.
    if let Some(c) = glm_parse_json(text, tools) {
      return Ok(vec![c]);
    }
    if let Some(c) = glm_parse_plain(text, tools) {
      return Ok(vec![c]);
    }
    Ok(vec![ToolCall::new(
      "unknown",
      serde_json::json!({"raw": text.trim()}),
    )])
  }
  fn name(&self) -> &'static str {
    "glm47"
  }
}

fn normalize_arguments(
  func_name: &str,
  arguments: &serde_json::Map<String, Value>,
  tools: Option<&Value>,
) -> serde_json::Map<String, Value> {
  let string_args = string_arg_names(tools, func_name);
  let mut out = serde_json::Map::new();
  for (k, v) in arguments {
    if string_args.contains(k) {
      let coerced = match v {
        Value::String(s) => Value::String(s.clone()),
        other => Value::String(other.to_string()),
      };
      out.insert(k.clone(), coerced);
    } else if let Value::String(s) = v {
      out.insert(k.clone(), deserialize(s));
    } else {
      out.insert(k.clone(), v.clone());
    }
  }
  out
}

fn glm_parse_json(text: &str, tools: Option<&Value>) -> Option<ToolCall> {
  let parsed: Value = serde_json::from_str(text.trim()).ok()?;
  let parsed = match &parsed {
    Value::Array(a) if !a.is_empty() && a[0].is_object() => a[0].clone(),
    _ => parsed,
  };
  let p = parsed.as_object()?;
  let (mut name, mut arguments) = if p.contains_key("name") && p.contains_key("arguments") {
    (p.get("name").cloned(), p.get("arguments").cloned())
  } else if p.contains_key("function") && p.contains_key("arguments") {
    (p.get("function").cloned(), p.get("arguments").cloned())
  } else if let Some(t) = p.get("tool").and_then(Value::as_object) {
    (t.get("name").cloned(), t.get("arguments").cloned())
  } else {
    (None, None)
  };
  if let Some(Value::Object(nm)) = &name {
    if arguments.is_none() {
      arguments = nm.get("arguments").cloned();
    }
    name = nm.get("name").cloned();
  }
  if let Some(Value::String(s)) = &arguments {
    arguments = Some(deserialize(s));
  }
  let name = name.and_then(|n| n.as_str().map(str::to_owned))?;
  match arguments {
    None => Some(ToolCall::new(name, serde_json::json!({}))),
    Some(Value::Object(m)) => {
      let norm = normalize_arguments(&name, &m, tools);
      Some(ToolCall::new(name, Value::Object(norm)))
    }
    _ => None,
  }
}

fn glm_parse_plain(text: &str, tools: Option<&Value>) -> Option<ToolCall> {
  let stripped = text.trim();
  if stripped.is_empty() {
    return None;
  }
  if let Some(nl) = stripped.find('\n') {
    let name = stripped[..nl].trim().to_owned();
    let rest = stripped[nl + 1..].trim();
    if !name.is_empty()
      && !rest.is_empty()
      && let Value::Object(m) = deserialize(rest)
    {
      let norm = normalize_arguments(&name, &m, tools);
      return Some(ToolCall::new(name, Value::Object(norm)));
    }
  }
  let (name, rest) = match stripped.split_once(' ') {
    Some((n, r)) => (n.to_owned(), r.trim().to_owned()),
    None => (stripped.to_owned(), String::new()),
  };
  if name.is_empty() {
    return None;
  }
  if rest.is_empty() {
    return Some(ToolCall::new(name, serde_json::json!({})));
  }
  if let Value::Object(m) = deserialize(&rest) {
    let norm = normalize_arguments(&name, &m, tools);
    return Some(ToolCall::new(name, Value::Object(norm)));
  }
  // key=value pairs
  if rest.contains('=') {
    let mut args = serde_json::Map::new();
    let string_args = string_arg_names(tools, &name);
    let mut ok = true;
    for token in rest.split_whitespace() {
      match token.split_once('=') {
        Some((k, v)) if !k.trim().is_empty() => {
          let key = k.trim().to_owned();
          if string_args.contains(&key) {
            args.insert(key, Value::String(v.to_owned()));
          } else {
            args.insert(key, deserialize(v));
          }
        }
        _ => {
          ok = false;
          break;
        }
      }
    }
    if ok && !args.is_empty() {
      return Some(ToolCall::new(name, Value::Object(args)));
    }
  }
  Some(ToolCall::new(name, serde_json::json!({"raw": rest})))
}

/// Find `(key, value)` pairs delimited by two open/close tag pairs.
fn find_kv_pairs(text: &str, ko: &str, kc: &str, vo: &str, vc: &str) -> Vec<(String, String)> {
  let mut out = Vec::new();
  let mut i = 0;
  while let Some(ks) = text[i..].find(ko) {
    let kabs = i + ks + ko.len();
    let Some(ke) = text[kabs..].find(kc) else {
      break;
    };
    let key = text[kabs..kabs + ke].to_owned();
    let after = kabs + ke + kc.len();
    let Some(vs) = text[after..].find(vo) else {
      break;
    };
    let vabs = after + vs + vo.len();
    let Some(ve) = text[vabs..].find(vc) else {
      break;
    };
    let val = text[vabs..vabs + ve].to_owned();
    out.push((key, val));
    i = vabs + ve + vc.len();
  }
  out
}

// ----------------------------------------------------------------------------
// kimi_k2: <|tool_call_begin|>functions.name:0<|tool_call_argument_begin|>{json}<|tool_call_end|>
// ----------------------------------------------------------------------------

/// `kimi_k2` — `<|tool_call_begin|>functions.name:0<|tool_call_argument_begin|>{json}<|tool_call_end|>`.
pub struct KimiK2;

impl KimiK2 {
  fn parse_single(text: &str) -> Result<ToolCall, Error> {
    let abeg = "<|tool_call_argument_begin|>";
    let abeg_idx = text
      .find(abeg)
      .ok_or_else(|| err("kimi_k2: No tool call found."))?;
    let head = text[..abeg_idx].trim();
    // ^\s*((?:functions\.)?(.+?):\d+)\s*
    let colon = head
      .rfind(':')
      .ok_or_else(|| err("kimi_k2: No tool call found."))?;
    if head[colon + 1..].trim().parse::<u64>().is_err() {
      return Err(err("kimi_k2: No tool call found."));
    }
    let full_id = head.to_owned();
    let base = &head[..colon];
    let func_name = base.strip_prefix("functions.").unwrap_or(base).to_owned();
    let args_part = text[abeg_idx + abeg.len()..].trim();
    let arg = deserialize(args_part);
    Ok(ToolCall {
      name: func_name,
      arguments: arg,
      id: Some(full_id),
    })
  }
}

impl ToolParser for KimiK2 {
  fn parse(&self, text: &str, _tools: Option<&Value>) -> Result<Vec<ToolCall>, Error> {
    let matches = find_all(text, "<|tool_call_begin|>", "<|tool_call_end|>");
    if matches.is_empty() {
      Ok(vec![Self::parse_single(text)?])
    } else {
      matches.iter().map(|m| Self::parse_single(m)).collect()
    }
  }
  fn name(&self) -> &'static str {
    "kimi_k2"
  }
}

// ----------------------------------------------------------------------------
// longcat
// ----------------------------------------------------------------------------

/// `longcat` — `name<longcat_arg_key>k</longcat_arg_key><longcat_arg_value>v</longcat_arg_value>`.
pub struct Longcat;

impl ToolParser for Longcat {
  fn parse(&self, text: &str, tools: Option<&Value>) -> Result<Vec<ToolCall>, Error> {
    let text = text.trim();
    if text.starts_with('{')
      && let Ok(v) = serde_json::from_str::<Value>(text)
    {
      // Python `longcat` returns the raw parsed dict here. We surface its
      // `name` / `arguments` (falling back to the whole object) so callers
      // still get a structured ToolCall.
      let name = v
        .get("name")
        .and_then(Value::as_str)
        .unwrap_or("")
        .to_owned();
      let args = match v.get("arguments") {
        Some(a) => a.clone(),
        None => v,
      };
      return Ok(obj(&name, args));
    }
    let idx = text
      .find("<longcat_arg_key>")
      .ok_or_else(|| err("longcat: no function name"))?;
    let func_name = text[..idx].trim().to_owned();
    let string_args = string_arg_names(tools, &func_name);
    let mut args = serde_json::Map::new();
    for (k, v) in find_kv_pairs(
      text,
      "<longcat_arg_key>",
      "</longcat_arg_key>",
      "<longcat_arg_value>",
      "</longcat_arg_value>",
    ) {
      let key = k.trim().to_owned();
      let val = if string_args.contains(&key) {
        Value::String(v.trim().to_owned())
      } else {
        deserialize(v.trim())
      };
      args.insert(key, val);
    }
    Ok(obj(&func_name, Value::Object(args)))
  }
  fn name(&self) -> &'static str {
    "longcat"
  }
}

// ----------------------------------------------------------------------------
// minimax_m2: <invoke name="n"><parameter name="p">v</parameter></invoke>
// ----------------------------------------------------------------------------

/// `minimax_m2` — `<invoke name="n"><parameter name="p">v</parameter></invoke>`.
pub struct MinimaxM2;

fn extract_name(s: &str) -> String {
  let s = s.trim();
  if (s.starts_with('"') && s.ends_with('"') && s.len() >= 2)
    || (s.starts_with('\'') && s.ends_with('\'') && s.len() >= 2)
  {
    s[1..s.len() - 1].to_owned()
  } else {
    s.to_owned()
  }
}

fn schema_types(schema: &Value) -> Vec<String> {
  let mut types = std::collections::BTreeSet::new();
  if let Some(o) = schema.as_object() {
    match o.get("type") {
      Some(Value::String(s)) => {
        types.insert(s.clone());
      }
      Some(Value::Array(a)) => {
        for t in a {
          if let Some(s) = t.as_str() {
            types.insert(s.to_owned());
          }
        }
      }
      _ => {}
    }
    if let Some(Value::Array(en)) = o.get("enum") {
      for v in en {
        types.insert(
          match v {
            Value::Null => "null",
            Value::Bool(_) => "boolean",
            Value::Number(n) if n.is_i64() || n.is_u64() => "integer",
            Value::Number(_) => "number",
            Value::String(_) => "string",
            Value::Array(_) => "array",
            Value::Object(_) => "object",
          }
          .to_owned(),
        );
      }
    }
    for cf in ["anyOf", "oneOf", "allOf"] {
      if let Some(Value::Array(a)) = o.get(cf) {
        for c in a {
          for t in schema_types(c) {
            types.insert(t);
          }
        }
      }
    }
  }
  if types.is_empty() {
    vec!["string".to_owned()]
  } else {
    types.into_iter().collect()
  }
}

fn convert_with_types(value: &str, ptypes: &[String]) -> Value {
  if value.eq_ignore_ascii_case("null") {
    return Value::Null;
  }
  let norm: Vec<String> = ptypes.iter().map(|t| t.to_lowercase()).collect();
  let lv = value.to_lowercase();
  if norm.iter().any(|t| t == "null") || ["null", "none", "nil"].contains(&lv.as_str()) {
    return Value::Null;
  }
  for pt in [
    "integer", "int", "number", "float", "boolean", "bool", "object", "array", "string", "str",
    "text",
  ] {
    if !norm.iter().any(|t| t == pt) {
      continue;
    }
    match pt {
      "string" | "str" | "text" => return Value::String(value.to_owned()),
      "integer" | "int" => {
        if let Ok(i) = value.parse::<i64>() {
          return Value::Number(i.into());
        }
      }
      "number" | "float" => {
        if let Ok(f) = value.parse::<f64>() {
          return if f.fract() == 0.0 {
            Value::Number((f as i64).into())
          } else {
            serde_json::Number::from_f64(f)
              .map(Value::Number)
              .unwrap_or(Value::Null)
          };
        }
      }
      "boolean" | "bool" => {
        let l = value.trim().to_lowercase();
        if ["true", "1", "yes", "on"].contains(&l.as_str()) {
          return Value::Bool(true);
        }
        if ["false", "0", "no", "off"].contains(&l.as_str()) {
          return Value::Bool(false);
        }
      }
      "object" | "array" => {
        if let Ok(v) = serde_json::from_str::<Value>(value) {
          return v;
        }
      }
      _ => {}
    }
  }
  serde_json::from_str::<Value>(value).unwrap_or_else(|_| Value::String(value.to_owned()))
}

impl ToolParser for MinimaxM2 {
  fn parse(&self, text: &str, tools: Option<&Value>) -> Result<Vec<ToolCall>, Error> {
    let invokes = find_all(text, "<invoke name=", "</invoke>");
    if invokes.is_empty() {
      return Err(err("minimax_m2: No tool call found"));
    }
    let mut calls = Vec::new();
    for inv in &invokes {
      let name_seg = inv.split('>').next().unwrap_or("");
      let function_name = extract_name(name_seg);
      let props = tool_properties(tools, &function_name);
      let mut args = serde_json::Map::new();
      for pm in find_all(inv, "<parameter name=", "</parameter>") {
        let gt = match pm.find('>') {
          Some(g) => g,
          None => continue,
        };
        let pname = extract_name(&pm[..gt]);
        let mut pval = pm[gt + 1..].trim().to_owned();
        if let Some(r) = pval.strip_prefix('\n') {
          pval = r.to_owned();
        }
        if let Some(r) = pval.strip_suffix('\n') {
          pval = r.to_owned();
        }
        let ptypes = props
          .and_then(|p| p.get(&pname))
          .map(schema_types)
          .unwrap_or_else(|| vec!["string".to_owned()]);
        args.insert(pname, convert_with_types(&pval, &ptypes));
      }
      calls.push(ToolCall::new(&function_name, Value::Object(args)));
    }
    Ok(calls)
  }
  fn name(&self) -> &'static str {
    "minimax_m2"
  }
}

// ----------------------------------------------------------------------------
// function_gemma: call:name{k:v,...} with <escape> string markers
// ----------------------------------------------------------------------------

/// `function_gemma` — `call:name{k:v,...}` with `<escape>`-delimited strings.
pub struct FunctionGemma;

impl ToolParser for FunctionGemma {
  fn parse(&self, text: &str, _tools: Option<&Value>) -> Result<Vec<ToolCall>, Error> {
    // call:(\w+)\{(.*?)\}
    let (func_name, mut args_str) =
      gemma_call(text, false).ok_or_else(|| err("function_gemma: No function provided."))?;
    let mut arguments = serde_json::Map::new();
    let escape = "<escape>";
    while !args_str.is_empty() {
      let split = match args_str.find(':') {
        Some(s) => s,
        None => break,
      };
      let key = args_str[..split].to_owned();
      args_str = args_str[split + 1..].to_owned();
      if let Some(rest) = args_str.strip_prefix(escape)
        && let Some(end) = rest.find(escape)
      {
        arguments.insert(key, Value::String(rest[..end].to_owned()));
        // Python: `args_str = args_str[split + len(escape) + 1:]` — the `+1`
        // skips the trailing `,`. `end + escape.len()` is a char boundary
        // (just past the ASCII `<escape>`); the extra byte is only valid if
        // it is the 1-byte ASCII `,`. A non-ASCII char there must not slice
        // mid-UTF-8 — surface a parse `Error` instead of panicking.
        let after_escape = end + escape.len();
        let consumed = after_escape + 1;
        args_str = if consumed >= rest.len() {
          String::new()
        } else if rest.is_char_boundary(consumed) {
          rest[consumed..].to_owned()
        } else {
          return Err(err("function_gemma: malformed argument encoding"));
        };
        continue;
      }
      let split = args_str.find(',').unwrap_or(args_str.len());
      let value = args_str[..split].to_owned();
      args_str = if split < args_str.len() {
        args_str[(split + 1).min(args_str.len())..].to_owned()
      } else {
        String::new()
      };
      let v =
        serde_json::from_str::<Value>(&value).unwrap_or_else(|_| Value::String(value.clone()));
      arguments.insert(key, v);
    }
    Ok(obj(&func_name, Value::Object(arguments)))
  }
  fn name(&self) -> &'static str {
    "function_gemma"
  }
}

/// Find `call:name{...}` — non-greedy `{.*?}` when `balanced` is false.
fn gemma_call(text: &str, _balanced: bool) -> Option<(String, String)> {
  let s = text.find("call:")?;
  let after = &text[s + 5..];
  let mut j = 0;
  let bytes = after.as_bytes();
  while j < bytes.len()
    && (bytes[j].is_ascii_alphanumeric() || bytes[j] == b'_' || bytes[j] == b'-')
  {
    j += 1;
  }
  if j == 0 || j >= bytes.len() || bytes[j] != b'{' {
    return None;
  }
  let name = after[..j].to_owned();
  let rest = &after[j + 1..];
  let close = rest.find('}')?;
  Some((name, rest[..close].to_owned()))
}

// ----------------------------------------------------------------------------
// gemma4: call:name{bare_keys: <|"|>str<|"|>, ...} with balanced braces
// ----------------------------------------------------------------------------

/// `gemma4` — `call:name{key: <|"|>string<|"|>, n: 2}` with bare keys, `<|"|>`
/// string delimiters and balanced nested braces.
pub struct Gemma4;

impl ToolParser for Gemma4 {
  fn parse(&self, text: &str, _tools: Option<&Value>) -> Result<Vec<ToolCall>, Error> {
    let calls = gemma4_calls(text);
    if calls.is_empty() {
      return Err(err("gemma4: No function provided."));
    }
    let mut out = Vec::new();
    for (name, args_str) in calls {
      let json_str = gemma4_args_to_json(&args_str);
      let arguments: Value =
        serde_json::from_str(&json_str).map_err(|e| err(format!("gemma4: {e}")))?;
      out.push(ToolCall::new(&name, arguments));
    }
    Ok(out)
  }
  fn name(&self) -> &'static str {
    "gemma4"
  }
}

/// Find all `call:name{...}` with balanced braces, ignoring braces inside
/// `<|"|>...<|"|>` string literals.
fn gemma4_calls(text: &str) -> Vec<(String, String)> {
  let mut out = Vec::new();
  let mut i = 0;
  while let Some(s) = text[i..].find("call:") {
    let abs = i + s + 5;
    let after = &text[abs..];
    let mut j = 0;
    let b = after.as_bytes();
    while j < b.len() && (b[j].is_ascii_alphanumeric() || b[j] == b'_' || b[j] == b'-') {
      j += 1;
    }
    if j == 0 || j >= b.len() || b[j] != b'{' {
      i = abs;
      continue;
    }
    let name = after[..j].to_owned();
    let body = &after[j..];
    if let Some(end) = balanced_brace_end(body) {
      out.push((name, body[..=end].to_owned()));
      i = abs + j + end + 1;
    } else {
      i = abs + j;
    }
  }
  out
}

/// Given text starting with `{`, return the index of the matching `}`,
/// skipping `<|"|>...<|"|>` literals.
fn balanced_brace_end(s: &str) -> Option<usize> {
  let bytes = s.as_bytes();
  if bytes.first() != Some(&b'{') {
    return None;
  }
  let lit = "<|\"|>";
  let mut depth = 0usize;
  let mut idx = 0;
  while idx < s.len() {
    if s[idx..].starts_with(lit) {
      // skip to closing literal
      let close = s[idx + lit.len()..].find(lit)?;
      idx = idx + lit.len() + close + lit.len();
      continue;
    }
    match bytes[idx] {
      b'{' => depth += 1,
      b'}' => {
        depth -= 1;
        if depth == 0 {
          return Some(idx);
        }
      }
      _ => {}
    }
    // Advance by the full UTF-8 width of the char at `idx`, not a single
    // byte: a non-ASCII char inside the braces would otherwise leave `idx`
    // mid-codepoint and panic on the next `s[idx..]` slice. ASCII (the only
    // structural chars: `{` `}` and the literal) is unaffected (width 1).
    idx += utf8_char_width(bytes[idx]);
  }
  None
}

/// UTF-8 encoded width (1..=4) of the char whose first byte is `b`. A stray
/// continuation byte yields 1 so the scan still makes progress instead of
/// looping or panicking on malformed input.
#[inline]
fn utf8_char_width(b: u8) -> usize {
  match b {
    0x00..=0x7F => 1,
    0xC0..=0xDF => 2,
    0xE0..=0xEF => 3,
    0xF0..=0xF7 => 4,
    _ => 1,
  }
}

fn gemma4_args_to_json(text: &str) -> String {
  // Extract <|"|>...<|"|> strings into placeholders.
  let lit = "<|\"|>";
  let mut strings: Vec<String> = Vec::new();
  let mut result = String::new();
  let mut i = 0;
  while i < text.len() {
    if text[i..].starts_with(lit)
      && let Some(close) = text[i + lit.len()..].find(lit)
    {
      let inner = &text[i + lit.len()..i + lit.len() + close];
      result.push('\u{0}');
      result.push_str(&strings.len().to_string());
      result.push('\u{0}');
      strings.push(inner.to_owned());
      i = i + lit.len() + close + lit.len();
      continue;
    }
    let ch = text[i..].chars().next().unwrap();
    result.push(ch);
    i += ch.len_utf8();
  }
  // Quote bare keys: (?<=[{,])(\w+):  -> "\1":
  let mut quoted = String::new();
  let rb = result.as_bytes();
  let mut k = 0;
  while k < result.len() {
    let c = rb[k];
    quoted.push(c as char);
    if c == b'{' || c == b',' {
      // read following \w+ then ':'
      let mut m = k + 1;
      while m < rb.len() && (rb[m].is_ascii_alphanumeric() || rb[m] == b'_') {
        m += 1;
      }
      if m > k + 1 && m < rb.len() && rb[m] == b':' {
        quoted.push('"');
        quoted.push_str(&result[k + 1..m]);
        quoted.push('"');
        quoted.push(':');
        k = m + 1;
        continue;
      }
    }
    k += 1;
  }
  // Restore captured strings as JSON-escaped strings.
  for (idx, sv) in strings.iter().enumerate() {
    let placeholder = format!("\u{0}{idx}\u{0}");
    let json = serde_json::to_string(sv).unwrap_or_else(|_| "\"\"".into());
    quoted = quoted.replace(&placeholder, &json);
  }
  quoted
}

// ----------------------------------------------------------------------------
// Selection
// ----------------------------------------------------------------------------

/// Build a boxed parser by Python module name. Returns `None` for unknown
/// names (mirrors importlib failing silently into "no parser").
pub fn parser_by_name(name: &str) -> Option<Box<dyn ToolParser>> {
  Some(match name {
    "json_tools" => Box::new(JsonTools),
    "pythonic" => Box::new(Pythonic),
    "mistral" => Box::new(Mistral),
    "qwen3_coder" => Box::new(Qwen3Coder),
    "glm47" => Box::new(Glm47),
    "kimi_k2" => Box::new(KimiK2),
    "longcat" => Box::new(Longcat),
    "minimax_m2" => Box::new(MinimaxM2),
    "function_gemma" => Box::new(FunctionGemma),
    "gemma4" => Box::new(Gemma4),
    _ => return None,
  })
}

/// Auto-infer a tool-parser name from a chat-template string. Direct port of
/// Python `_infer_tool_parser` (`tokenizer_utils.py` ~548), order-preserving.
///
/// The selection chain is the `cargo xtask-codegen`-generated
/// `TOOL_PARSER_SELECT` table (sourced from
/// `mlxrs/data/tokenizer/tool_parsers.toml`, mlx-lm df1d3f3),
/// walked in declaration order: the first rule whose `all` substrings are all
/// present *and* (`any_of` empty or one present) wins — semantically
/// identical to the Python if/elif chain.
pub fn infer_tool_parser(chat_template: Option<&str>) -> Option<&'static str> {
  let ct = chat_template?;
  for rule in TOOL_PARSER_SELECT {
    let all_ok = rule.all.iter().all(|s| ct.contains(s));
    let any_ok = rule.any_of.is_empty() || rule.any_of.iter().any(|s| ct.contains(s));
    if all_ok && any_ok {
      return Some(rule.name);
    }
  }
  None
}

// ----------------------------------------------------------------------------
// Streaming processor
// ----------------------------------------------------------------------------

/// Strip the parser's `tool_call_start` / `tool_call_end` delimiters from a
/// buffered tool-call payload, returning the trimmed inner text.
///
/// In `mlx-swift-lm` each `ToolCallParser` strips its own tags inside `parse`
/// (e.g. `JSONToolCallParser` removes `<tool_call>` / `</tool_call>`). mlxrs
/// keeps delimiters in one shared marker table instead, so the streaming
/// processor strips them centrally before delegating — the existing
/// [`ToolParser`]s expect the bare payload (`JsonTools` feeds the body
/// straight to `serde_json`; the tag-scanning parsers are unaffected because
/// stripping a delimiter they would only have searched for is idempotent).
/// Only the first start tag and the last end tag are removed, matching the
/// Swift `range(of:)` strip; literal delimiter text inside argument values is
/// otherwise preserved.
fn strip_markers<'a>(parser: &dyn ToolParser, buffer: &'a str) -> &'a str {
  let mut text = buffer;
  let start = parser.tool_call_start();
  if !start.is_empty()
    && let Some(idx) = text.find(start)
  {
    text = &text[idx + start.len()..];
  }
  let end = parser.tool_call_end();
  if !end.is_empty()
    && let Some(idx) = text.rfind(end)
  {
    text = &text[..idx];
  }
  text.trim()
}

/// Streaming `parseEOS` over a [`ToolParser`], mirroring the default
/// `ToolCallParser.parseEOS` extension in `mlx-swift-lm`
/// (`MLXLMCommon/Tool/ToolCallFormat.swift`).
///
/// When the parser has a non-empty `tool_call_start`, the buffer is split on
/// it and every non-empty segment is parsed individually; otherwise the whole
/// buffer is parsed once. A segment that fails to parse is dropped (Swift
/// `compactMap`), so a malformed tail can never panic the stream. Each
/// segment has its end tag stripped via [`strip_markers`] before delegating.
fn parse_eos(parser: &dyn ToolParser, buffer: &str, tools: Option<&Value>) -> Vec<ToolCall> {
  let start = parser.tool_call_start();
  if start.is_empty() {
    let inner = strip_markers(parser, buffer);
    return parser.parse(inner, tools).unwrap_or_default();
  }
  buffer
    .split(start)
    .filter(|seg| !seg.is_empty())
    .filter_map(|seg| parser.parse(strip_markers(parser, seg), tools).ok())
    .flatten()
    .collect()
}

/// Bound on the streaming tool-call buffer, in bytes.
///
/// Once a chunk has entered `PotentialToolCall` or `CollectingToolCall` every
/// subsequent chunk is appended until an end tag / balanced JSON / EOS
/// arrives. A malformed or adversarial generation (inline JSON whose braces
/// never balance, or a tagged format — including Mistral's empty end tag —
/// whose end tag never appears) would otherwise let the buffer grow without
/// bound and OOM before EOS (Codex finding 2).
///
/// 256 KiB is far larger than any genuine tool-call payload (function names +
/// JSON arguments are kilobytes at most) yet small enough that retaining it is
/// harmless. After **each** chunk is appended the buffer length is checked
/// against this cap; on exceeding it `ToolCallProcessor` *recovers* rather
/// than panics (see `recover_at_cap`): a not-yet-confirmed start flushes the
/// buffered bytes back as ordinary display text; a confirmed-but-overlong tool
/// call drops the buffer. Either way the buffer is then emptied and the state
/// reset, so growth is `O(1)` per generation rather than `O(total output)` —
/// the buffer peaks at this cap plus at most one chunk (a single detokenized
/// token's worth of text), never unbounded.
const MAX_TOOL_CALL_BUFFER_BYTES: usize = 256 * 1024;

/// Streaming state-machine for detecting and extracting tool calls while a
/// model is still generating, fed text chunk-by-chunk.
///
/// Direct port of `mlx-swift-lm`'s `ToolCallProcessor`
/// (`MLXLMCommon/Tool/ToolCallProcessor.swift`): partial content is buffered
/// so a half-finished tool call is never leaked to the UI, and a complete
/// tool call is extracted into [`tool_calls`](Self::tool_calls) the moment its
/// closing delimiter (or balanced JSON) arrives. It reuses the per-format
/// [`ToolParser`]s above rather than re-implementing any parsing.
///
/// Two delimiter regimes, dispatched on whether the parser has a start tag:
///
/// - **Tagged** (`tool_call_start` non-empty, e.g. `json_tools`'
///   `<tool_call>`): the buffer is matched against the start tag character by
///   character; once the full start tag is seen the state advances to
///   collecting, and the call is parsed when the end tag arrives.
/// - **Inline** (`tool_call_start` empty): a JSON-string-aware balanced-object
///   scan drives detection — while the JSON object is still open the content
///   is buffered; a complete object that fails to parse is flushed back out as
///   ordinary text, and any text *after* the object is processed separately so
///   extraction does not depend on chunk boundaries.
///
/// The buffer is bounded by an internal `MAX_TOOL_CALL_BUFFER_BYTES` cap: a
/// malformed stream that never completes a tool call recovers (false starts
/// flush as display text, runaway tool content is dropped) instead of growing
/// without bound.
///
/// # Example
///
/// ```
/// use mlxrs::tokenizer::tools::{JsonTools, ToolCallProcessor};
///
/// let mut proc = ToolCallProcessor::new(Box::new(JsonTools), None);
/// // Regular text passes straight through.
/// assert_eq!(proc.process_chunk("Sure! ").as_deref(), Some("Sure! "));
/// // A tool call split across chunks is buffered (returns `None`) ...
/// assert_eq!(proc.process_chunk("<tool_call>{\"name\": \"now\","), None);
/// // ... and emitted once its end tag arrives.
/// assert_eq!(proc.process_chunk("\"arguments\": {}}</tool_call>"), None);
/// assert_eq!(proc.tool_calls.len(), 1);
/// assert_eq!(proc.tool_calls[0].name, "now");
/// ```
pub struct ToolCallProcessor {
  /// The per-format parser the state machine delegates structured parsing to.
  parser: Box<dyn ToolParser>,
  /// Optional tool schemas forwarded to the parser for type-aware coercion.
  tools: Option<Value>,
  /// Current state machine position.
  state: State,
  /// Buffered partial tool-call text not yet emitted or parsed.
  tool_call_buffer: String,
  /// Tool calls extracted so far, in arrival order.
  pub tool_calls: Vec<ToolCall>,
}

/// State-machine position (Swift `ToolCallProcessor.State`).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum State {
  /// Passing generated text straight through; no tool call in progress.
  Normal,
  /// A start-tag prefix has been seen; still confirming it is a real tag.
  PotentialToolCall,
  /// Inside a confirmed tool call, buffering until it completes.
  CollectingToolCall,
}

impl ToolCallProcessor {
  /// Create a processor driving `parser`, with optional `tools` schemas for
  /// type-aware argument coercion.
  pub fn new(parser: Box<dyn ToolParser>, tools: Option<Value>) -> Self {
    Self {
      parser,
      tools,
      state: State::Normal,
      tool_call_buffer: String::new(),
      tool_calls: Vec::new(),
    }
  }

  /// Whether this processor uses an inline format (no start tag).
  fn is_inline_format(&self) -> bool {
    self.parser.tool_call_start().is_empty()
  }

  /// The first `char` of the start tag, for quick chunk pre-screening.
  fn start_tag_first_char(&self) -> Option<char> {
    self.parser.tool_call_start().chars().next()
  }

  /// Process one generated text chunk.
  ///
  /// Returns the regular (non-tool-call) text that should be displayed, or
  /// `None` while partial tool-call content is being buffered.
  pub fn process_chunk(&mut self, chunk: &str) -> Option<String> {
    if self.is_inline_format() {
      self.process_inline_chunk(chunk)
    } else {
      self.process_tagged_chunk(chunk)
    }
  }

  /// Process end-of-sequence, parsing any buffered content as tool call(s).
  ///
  /// Call this when generation ends (e.g. on an EOS token) to handle formats
  /// whose end tag is never delivered as text (e.g. `mistral`, whose `</s>`
  /// is intercepted at the token-ID level). For formats whose end tag does
  /// appear in the text stream the buffer is already empty here, making this
  /// a no-op.
  pub fn process_eos(&mut self) {
    if self.state != State::CollectingToolCall && self.state != State::PotentialToolCall {
      return;
    }
    if self.tool_call_buffer.is_empty() {
      self.state = State::Normal;
      return;
    }
    let parsed = parse_eos(
      self.parser.as_ref(),
      &self.tool_call_buffer,
      self.tools.as_ref(),
    );
    self.tool_calls.extend(parsed);
    self.tool_call_buffer.clear();
    self.state = State::Normal;
  }

  /// Run the parser against the current buffer (with delimiters stripped),
  /// treating an `Err` as a failed parse (Swift returns `nil`). On success any
  /// extracted calls are appended; returns `true` when at least one call was
  /// extracted.
  fn try_parse_buffer(&mut self) -> bool {
    let inner = strip_markers(self.parser.as_ref(), &self.tool_call_buffer);
    let parsed = self.parser.parse(inner, self.tools.as_ref());
    match parsed {
      Ok(calls) if !calls.is_empty() => {
        self.tool_calls.extend(calls);
        true
      }
      _ => false,
    }
  }

  /// Recover when [`tool_call_buffer`](Self::tool_call_buffer) has reached
  /// [`MAX_TOOL_CALL_BUFFER_BYTES`] without the tool call completing.
  ///
  /// This enforces the bounded-memory contract (Codex finding 2): the buffer
  /// is *always* emptied here and the state reset to [`State::Normal`], so it
  /// can never grow past the cap. The recovery action depends on how far
  /// detection had progressed:
  ///
  /// - [`State::PotentialToolCall`] — the start tag was never confirmed, so
  ///   the buffered bytes are (at worst) a false start; they are flushed back
  ///   to the caller verbatim as ordinary display text, losing nothing.
  /// - [`State::CollectingToolCall`] — a real tool call was in progress but is
  ///   pathologically long / never terminates; its partial content is dropped
  ///   (it is not valid display text and cannot be parsed) and `None` is
  ///   returned. This is a clear "give up on this call" signal, never a panic.
  /// - [`State::Normal`] — unreachable (the buffer only fills past `Normal`);
  ///   handled defensively by flushing.
  ///
  /// Returns the text to display, if any.
  fn recover_at_cap(&mut self) -> Option<String> {
    let recovered = std::mem::take(&mut self.tool_call_buffer);
    let drop_as_malformed = self.state == State::CollectingToolCall;
    self.state = State::Normal;
    if drop_as_malformed {
      // Malformed / unbounded tool-call content — drop it, do not display.
      None
    } else {
      // False start (or defensive `Normal`) — the bytes are display text.
      Some(recovered)
    }
  }

  /// Enforce the buffer cap once per appended chunk.
  ///
  /// If `tool_call_buffer` has exceeded `MAX_TOOL_CALL_BUFFER_BYTES` this runs
  /// `recover_at_cap` and folds any flushed display text into `display`;
  /// otherwise it does nothing. Called from every buffering branch so the
  /// bound holds after each chunk regardless of which state the processor is
  /// in (Codex finding 2).
  fn cap_recover_into(&mut self, display: &mut Option<String>) {
    if self.tool_call_buffer.len() <= MAX_TOOL_CALL_BUFFER_BYTES {
      return;
    }
    if let Some(flushed) = self.recover_at_cap() {
      push_display(display, &flushed);
    }
  }

  /// Process a chunk for inline formats (no wrapper tags).
  ///
  /// Uses a JSON-string-aware balanced-object scan to decide when output
  /// looks like a JSON tool call. While the object is still open the content
  /// is buffered (returns `None`) so partial JSON is never leaked; a balanced
  /// buffer that fails to parse is not a tool call and is flushed back out.
  /// Any text *after* the first balanced JSON object in the same buffer is
  /// processed separately, so extraction never depends on where chunk
  /// boundaries fall (Codex finding 1).
  fn process_inline_chunk(&mut self, chunk: &str) -> Option<String> {
    // Leading display text in front of the first `{` of a *fresh* detection.
    let leading = match self.state {
      State::Normal => {
        let Some(brace) = chunk.find('{') else {
          // No brace seen — pass through as regular text.
          return Some(chunk.to_owned());
        };
        let leading = chunk[..brace].to_owned();
        self.tool_call_buffer.clear();
        self.tool_call_buffer.push_str(&chunk[brace..]);
        self.state = State::CollectingToolCall;
        leading
      }
      State::PotentialToolCall | State::CollectingToolCall => {
        self.tool_call_buffer.push_str(chunk);
        String::new()
      }
    };

    let mut display = self.drain_inline_buffer();

    // Bounded-memory guard (Codex finding 2): if the buffer is still holding
    // an unterminated JSON object after draining, recover (drop the runaway
    // content) instead of buffering without bound. No-op below the cap.
    if self.state == State::CollectingToolCall {
      self.cap_recover_into(&mut display);
    }

    // Prepend any leading text from this chunk.
    if leading.is_empty() {
      display
    } else {
      Some(leading + display.as_deref().unwrap_or(""))
    }
  }

  /// Iteratively consume balanced JSON-object prefixes from
  /// [`tool_call_buffer`](Self::tool_call_buffer).
  ///
  /// Each complete `{ ... }` object (string/escape aware — Codex finding 3) is
  /// parsed: a successful parse appends [`ToolCall`]s, a failed parse means
  /// "complete JSON that is not a tool call" and the object's bytes become
  /// display text. Whatever follows the object in the buffer is then examined
  /// again — extraction therefore never depends on chunk boundaries (Codex
  /// finding 1): `{...} done` and the same bytes split after `}` behave
  /// identically. Looping stops when the remainder is an incomplete object
  /// (kept buffered, state stays `CollectingToolCall`) or has no `{` left
  /// (any plain remainder is emitted and state returns to `Normal`).
  ///
  /// The loop is bounded by the strictly shrinking buffer (each iteration
  /// removes a non-empty prefix), so it is iterative with no recursion.
  fn drain_inline_buffer(&mut self) -> Option<String> {
    let mut display: Option<String> = None;
    loop {
      match balanced_json_object_prefix(&self.tool_call_buffer) {
        Some((obj_start, obj_end)) => {
          // A complete JSON object occupies `[obj_start..obj_end]`; anything
          // before `obj_start` is plain leading text, anything after
          // `obj_end` is a suffix to re-examine.
          if obj_start > 0 {
            push_display(&mut display, &self.tool_call_buffer[..obj_start]);
          }
          let object: String = self.tool_call_buffer[obj_start..obj_end].to_owned();
          let suffix: String = self.tool_call_buffer[obj_end..].to_owned();

          let inner = strip_markers(self.parser.as_ref(), &object);
          match self.parser.parse(inner, self.tools.as_ref()) {
            Ok(calls) if !calls.is_empty() => self.tool_calls.extend(calls),
            // Balanced JSON that is not a tool call — surface as display text.
            _ => push_display(&mut display, &object),
          }

          self.tool_call_buffer = suffix;
          if self.tool_call_buffer.is_empty() {
            self.state = State::Normal;
            return display;
          }
          // Re-examine the suffix on the next iteration.
        }
        None => {
          if self.tool_call_buffer.contains('{') {
            // An object is open but not yet closed — keep buffering.
            return display;
          }
          // No (more) JSON object — flush any plain remainder as display text.
          self.state = State::Normal;
          let remainder = std::mem::take(&mut self.tool_call_buffer);
          push_display(&mut display, &remainder);
          return display;
        }
      }
    }
  }

  /// Process a chunk for tagged formats.
  ///
  /// When the text after an end tag itself contains the start character there
  /// may be further back-to-back tool calls. This is handled by an explicit
  /// **loop** over that trailing suffix (Codex finding 4) — re-feeding it as
  /// the next chunk — rather than a recursive `process_chunk` self-call, so a
  /// single batched chunk packed with many tool calls cannot overflow the
  /// stack. Each iteration's output is concatenated in stream order, exactly
  /// matching the previous recursive behaviour.
  fn process_tagged_chunk(&mut self, chunk: &str) -> Option<String> {
    let start_tag = self.parser.tool_call_start();
    let Some(start_char) = self.start_tag_first_char() else {
      return Some(chunk.to_owned());
    };

    // The chunk currently being processed. After an end tag, the trailing
    // suffix is fed back here for the next loop iteration (no recursion).
    let mut chunk: std::borrow::Cow<'_, str> = std::borrow::Cow::Borrowed(chunk);
    // Display text accumulated across iterations, in stream order.
    let mut display: Option<String> = None;

    loop {
      // In `Normal`, ignore chunks that cannot begin a tag; once past `Normal`
      // every chunk is appended regardless.
      if self.state == State::Normal && !chunk.contains(start_char) {
        push_display(&mut display, &chunk);
        return display;
      }

      self.tool_call_buffer.push_str(&chunk);
      let mut leading_token: Option<String> = None;

      if self.state == State::Normal {
        // Advance to potential tool call, splitting off any leading text.
        self.state = State::PotentialToolCall;
        leading_token = separate_token(&mut self.tool_call_buffer, start_char, true);
      }

      if self.state == State::PotentialToolCall {
        if partial_match(&self.tool_call_buffer, start_tag) {
          if self.tool_call_buffer.starts_with(start_tag) {
            // Confirmed start tag — fall through to collecting. The text that
            // preceded the tag is now unambiguously display text, so emit it
            // in stream order *before* the call (Codex round-2 finding 1):
            // it must surface whether or not the end tag has streamed yet,
            // and identically to splitting the stream right before the tag.
            self.state = State::CollectingToolCall;
            push_display(&mut display, &leading_token.take().unwrap_or_default());
          } else {
            // Still an ambiguous start-tag prefix. `partial_match` only holds
            // here while the buffer is a *strict* prefix of `start_tag`, so it
            // is already bounded by the (tiny) tag length and cannot grow
            // unbounded — but apply the same cap defensively (Codex finding 2)
            // so the bound holds unconditionally regardless of tag length.
            self.cap_recover_into(&mut display);
            return display;
          }
        } else {
          // Not a tool call after all — return the collected text and reset.
          self.state = State::Normal;
          let buffer = std::mem::take(&mut self.tool_call_buffer);
          push_display(&mut display, &leading_token.unwrap_or_default());
          push_display(&mut display, &buffer);
          return display;
        }
      }

      // State::CollectingToolCall
      let end_tag = self.parser.tool_call_end();
      if end_tag.is_empty() {
        // No end tag (e.g. `mistral`): the call is closed at EOS, not
        // in-stream. With no closing delimiter the buffer would otherwise
        // grow without bound on a runaway generation (Codex finding 2).
        self.cap_recover_into(&mut display);
        return display;
      }

      // Locate the *real* end tag. For JSON-payload formats (`json_tools`) an
      // end delimiter inside a JSON string argument value must not be mistaken
      // for the close (Codex round-2 finding 2); `find_tagged_end_tag` uses a
      // JSON-string-aware scan there and the plain substring search otherwise.
      let end_at = find_tagged_end_tag(
        &self.tool_call_buffer,
        start_tag,
        end_tag,
        self.parser.tagged_payload_is_json(),
      );

      if let Some(end_at) = end_at {
        // Split the buffer at the confirmed end-tag offset: everything after
        // the end tag becomes the trailing token (Swift `separateToken` with
        // `returnLeading: false`), and the buffer keeps up to and including
        // the end tag for parsing.
        let after = end_at + end_tag.len();
        let trailing_token = self.tool_call_buffer[after..].to_owned();
        self.tool_call_buffer.truncate(after);

        self.try_parse_buffer();

        self.state = State::Normal;
        self.tool_call_buffer.clear();

        // If the trailing token holds the start char there may be more calls
        // — loop on it instead of recursing.
        if trailing_token.contains(start_char) {
          chunk = std::borrow::Cow::Owned(trailing_token);
          // Re-enter the loop with the trailing suffix as the next chunk.
        } else {
          push_display(&mut display, &trailing_token);
          return display;
        }
      } else {
        // End tag not yet seen — confirmed tool call still collecting. Cap the
        // buffer so a never-terminated tagged call cannot OOM (Codex finding
        // 2); recovery here drops the malformed content.
        self.cap_recover_into(&mut display);
        return display;
      }
    }
  }
}

/// Append `text` to an optional display accumulator, allocating the `String`
/// lazily so a pure-`None` (fully buffered) result stays `None`.
fn push_display(display: &mut Option<String>, text: &str) {
  if text.is_empty() {
    return;
  }
  display.get_or_insert_with(String::new).push_str(text);
}

/// Find the first balanced top-level JSON-*object* span of `text`.
///
/// Returns `(obj_start, obj_end)` byte offsets: `text[obj_start]` is the
/// first `{`, and `text[obj_start..obj_end]` is the shortest complete
/// `{ ... }` object (depth returns to zero). Returning the start as well as
/// the end lets the caller slice the object and its trailing suffix without a
/// second brace search, and process any suffix separately — fixing the
/// chunk-boundary dependency (Codex finding 1).
///
/// Unlike the Swift `jsonBracesBalanced` byte-counter this is JSON-string
/// aware: `{`/`}` inside a `"..."` string literal — including after a `\"`
/// escape — are not counted (Codex finding 3), so input such as
/// `{"unrelated":"}"}` is balanced correctly.
///
/// Scanning starts at the first `{`; bytes before it are ignored (they are
/// the caller's leading text). A `}` that would drive depth below zero makes
/// the object unparseable, so `None` is returned (the caller then flushes the
/// buffer as display text). `None` is also returned while the object is still
/// open (depth never returns to zero), meaning "keep buffering". Brace bytes
/// are ASCII, so every returned index is a UTF-8 char boundary even for
/// multibyte content inside string values.
fn balanced_json_object_prefix(text: &str) -> Option<(usize, usize)> {
  let bytes = text.as_bytes();
  let start = bytes.iter().position(|&b| b == b'{')?;
  let mut depth: i32 = 0;
  let mut in_string = false;
  let mut escaped = false;
  for (i, &b) in bytes.iter().enumerate().skip(start) {
    if in_string {
      if escaped {
        escaped = false;
      } else if b == b'\\' {
        escaped = true;
      } else if b == b'"' {
        in_string = false;
      }
      continue;
    }
    match b {
      b'"' => in_string = true,
      b'{' => depth += 1,
      b'}' => {
        depth -= 1;
        if depth == 0 {
          return Some((start, i + 1));
        }
        if depth < 0 {
          // More closes than opens: not a well-formed object prefix.
          return None;
        }
      }
      _ => {}
    }
  }
  None
}

/// Locate the byte offset of the *real* `end_tag` in a buffered **tagged**
/// tool call, accounting for the end delimiter possibly occurring inside the
/// payload (Codex round-2 finding 2).
///
/// Two regimes, selected by `payload_is_json`:
///
/// - **Non-JSON payloads** (`payload_is_json == false`): the payload cannot be
///   reasoned about structurally, so the end tag is the first substring match
///   — identical to the previous `contains` / `find` behaviour.
/// - **JSON payloads** (`payload_is_json == true`, e.g. `json_tools`): the
///   payload between `start_tag` and the end tag is exactly one JSON object.
///   A naive search would stop at an `end_tag` that is merely a character
///   sequence *inside a JSON string value* (`{"s":"</tool_call>"}`), cutting
///   the object in half. Instead the JSON-string-aware
///   [`balanced_json_object_prefix`] scanner finds where the object actually
///   closes, and the end tag is the first match **after** that close. While
///   the object is still open (`balanced_json_object_prefix` → `None`) no end
///   tag is accepted — any match so far is inside the unfinished object — so
///   the caller keeps buffering until the object completes.
///
/// Returns the offset (into `buffer`) at which `end_tag` begins, or `None`
/// when no end tag has been confirmed yet (keep collecting). `end_tag` is
/// assumed non-empty (callers handle the empty-end-tag formats separately).
fn find_tagged_end_tag(
  buffer: &str,
  start_tag: &str,
  end_tag: &str,
  payload_is_json: bool,
) -> Option<usize> {
  if !payload_is_json {
    return buffer.find(end_tag);
  }
  // The buffer of a confirmed tagged call starts with `start_tag`; the JSON
  // object is whatever follows it. If (defensively) it does not, fall back to
  // the naive search rather than mis-slicing.
  let payload_at = match buffer.find(start_tag) {
    Some(idx) => idx + start_tag.len(),
    None => return buffer.find(end_tag),
  };
  let payload = &buffer[payload_at..];
  // `balanced_json_object_prefix` is JSON-string aware: an `end_tag` inside a
  // `"..."` value is *within* `obj_end`, so the post-object search skips it.
  let (_, obj_end) = balanced_json_object_prefix(payload)?;
  // The end tag is the first occurrence strictly after the JSON object.
  let rel = payload[obj_end..].find(end_tag)?;
  Some(payload_at + obj_end + rel)
}

/// Split `buffer` on the first occurrence of the `char` `separator`, mirroring
/// Swift `separateToken(returnLeading:)`.
///
/// When `return_leading` is `true` the text *before* the separator is returned
/// and `buffer` keeps the separator onward; when `false` the text *after* is
/// returned and `buffer` keeps everything up to and including the separator.
/// Returns `None` (leaving `buffer` untouched) when the separator is absent.
fn separate_token(buffer: &mut String, separator: char, return_leading: bool) -> Option<String> {
  let idx = buffer.find(separator)?;
  if return_leading {
    let token = buffer[..idx].to_owned();
    buffer.replace_range(..idx, "");
    Some(token)
  } else {
    let after = idx + separator.len_utf8();
    let token = buffer[after..].to_owned();
    buffer.truncate(after);
    Some(token)
  }
}

/// Whether `buffer` is a prefix-compatible partial (or full) match of `tag`:
/// every char they share in order must be equal (Swift `partialMatch`). An
/// empty buffer trivially matches; a buffer longer than `tag` matches iff it
/// starts with `tag`.
fn partial_match(buffer: &str, tag: &str) -> bool {
  buffer.chars().zip(tag.chars()).all(|(b, t)| b == t)
}

#[cfg(test)]
mod tests {
  use super::*;

  /// Inline (no-tag) parser used to exercise the brace-counting code path of
  /// [`ToolCallProcessor`]: its `name()` is absent from the marker table, so
  /// both `tool_call_start` / `tool_call_end` resolve to `""`, just like the
  /// Swift `Llama3ToolCallParser` (`startTag == nil`). It parses a plain
  /// `{"name": ..., "arguments": ...}` JSON object.
  struct InlineJson;

  impl ToolParser for InlineJson {
    fn parse(&self, text: &str, _tools: Option<&Value>) -> Result<Vec<ToolCall>, Error> {
      let v: Value =
        serde_json::from_str(text.trim()).map_err(|e| err(format!("inline_json: {e}")))?;
      let name = v
        .get("name")
        .and_then(Value::as_str)
        .ok_or_else(|| err("inline_json: missing name"))?;
      let args = v.get("arguments").cloned().unwrap_or(Value::Null);
      Ok(obj(name, args))
    }
    fn name(&self) -> &'static str {
      "inline_json_test_parser"
    }
  }

  // --- tagged formats (json_tools: <tool_call>{json}</tool_call>) ----------

  #[test]
  fn streaming_tagged_json_single_chunk() {
    let mut p = ToolCallProcessor::new(Box::new(JsonTools), None);
    let out = p.process_chunk(r#"<tool_call>{"name": "get_time", "arguments": {}}</tool_call>"#);
    // Whole call consumed in one chunk: no display text leaks.
    assert_eq!(out, None);
    assert_eq!(p.tool_calls.len(), 1);
    assert_eq!(p.tool_calls[0].name, "get_time");
    assert_eq!(p.tool_calls[0].arguments, serde_json::json!({}));
  }

  #[test]
  fn streaming_tagged_json_split_across_chunks() {
    let mut p = ToolCallProcessor::new(Box::new(JsonTools), None);
    // Payload split in the middle of the JSON body.
    assert_eq!(
      p.process_chunk(r#"<tool_call>{"name": "get_weather", "#),
      None
    );
    assert_eq!(p.tool_calls.len(), 0); // not complete yet
    assert_eq!(
      p.process_chunk(r#""arguments": {"city": "Tokyo"}}</tool_call>"#),
      None
    );
    assert_eq!(p.tool_calls.len(), 1);
    assert_eq!(p.tool_calls[0].name, "get_weather");
    assert_eq!(
      p.tool_calls[0].arguments,
      serde_json::json!({"city": "Tokyo"})
    );
  }

  #[test]
  fn streaming_tagged_json_split_mid_token() {
    let mut p = ToolCallProcessor::new(Box::new(JsonTools), None);
    // The `<tool_call>` start tag itself is split mid-token across two feeds.
    assert_eq!(p.process_chunk("<tool_"), None); // partial tag — buffered
    assert_eq!(p.tool_calls.len(), 0);
    assert_eq!(
      p.process_chunk(r#"call>{"name": "ping", "arguments": {}}</tool_call>"#),
      None
    );
    assert_eq!(p.tool_calls.len(), 1);
    assert_eq!(p.tool_calls[0].name, "ping");
  }

  #[test]
  fn streaming_leading_text_then_tool_call() {
    let mut p = ToolCallProcessor::new(Box::new(JsonTools), None);
    // Leading prose in the same chunk as the start tag is display text and is
    // emitted as soon as the start tag is confirmed (Codex round-2 finding 1)
    // — it must not be silently dropped because the call completes later.
    let out = p.process_chunk(r#"Let me check. <tool_call>{"name": "ls", "arguments": {}}"#);
    assert_eq!(out.as_deref(), Some("Let me check. "));
    assert_eq!(p.process_chunk("</tool_call>"), None);
    assert_eq!(p.tool_calls.len(), 1);
    assert_eq!(p.tool_calls[0].name, "ls");
  }

  #[test]
  fn streaming_trailing_text_after_end_tag() {
    let mut p = ToolCallProcessor::new(Box::new(JsonTools), None);
    let out = p.process_chunk(r#"<tool_call>{"name": "ls", "arguments": {}}</tool_call> all done"#);
    // Text after the end tag is emitted as ordinary display text.
    assert_eq!(out.as_deref(), Some(" all done"));
    assert_eq!(p.tool_calls.len(), 1);
    assert_eq!(p.tool_calls[0].name, "ls");
  }

  #[test]
  fn streaming_multiple_tool_calls() {
    let mut p = ToolCallProcessor::new(Box::new(JsonTools), None);
    // Two back-to-back tool calls; the trailing token after the first end tag
    // holds the second start char, so processing recurses into it.
    let out = p.process_chunk(
      r#"<tool_call>{"name": "a", "arguments": {}}</tool_call><tool_call>{"name": "b", "arguments": {}}</tool_call>"#,
    );
    assert_eq!(out, None);
    assert_eq!(p.tool_calls.len(), 2);
    assert_eq!(p.tool_calls[0].name, "a");
    assert_eq!(p.tool_calls[1].name, "b");
  }

  // --- no tool call --------------------------------------------------------

  #[test]
  fn streaming_passthrough_no_tool_call() {
    let mut p = ToolCallProcessor::new(Box::new(JsonTools), None);
    // Plain generation with no tool call: every chunk passes straight through
    // and nothing is extracted.
    assert_eq!(
      p.process_chunk("The capital of France ").as_deref(),
      Some("The capital of France ")
    );
    assert_eq!(p.process_chunk("is Paris.").as_deref(), Some("is Paris."));
    p.process_eos();
    assert!(p.tool_calls.is_empty());
  }

  #[test]
  fn streaming_false_start_flushed() {
    let mut p = ToolCallProcessor::new(Box::new(JsonTools), None);
    // `<thinking>` shares the `<` start char but is not the `<tool_call>` tag:
    // the partial match fails and the buffered text is flushed back out.
    let out = p.process_chunk("<thinking>hmm</thinking>");
    assert_eq!(out.as_deref(), Some("<thinking>hmm</thinking>"));
    assert!(p.tool_calls.is_empty());
  }

  #[test]
  fn streaming_false_start_split_then_flushed() {
    let mut p = ToolCallProcessor::new(Box::new(JsonTools), None);
    // `<t` is a genuine prefix of `<tool_call>`, so it stays buffered as
    // ambiguous; only once `<thinking>` diverges from the tag is it flushed.
    assert_eq!(p.process_chunk("<t"), None); // still a valid tag prefix
    let out = p.process_chunk("hinking>");
    assert_eq!(out.as_deref(), Some("<thinking>"));
    assert!(p.tool_calls.is_empty());
  }

  // --- inline (no-tag) format: brace counting ------------------------------

  #[test]
  fn streaming_inline_single_chunk() {
    let mut p = ToolCallProcessor::new(Box::new(InlineJson), None);
    let out = p.process_chunk(r#"{"name": "now", "arguments": {}}"#);
    assert_eq!(out, None);
    assert_eq!(p.tool_calls.len(), 1);
    assert_eq!(p.tool_calls[0].name, "now");
  }

  #[test]
  fn streaming_inline_split_across_chunks() {
    let mut p = ToolCallProcessor::new(Box::new(InlineJson), None);
    // Unbalanced braces buffer; the call emits once balanced + parseable.
    assert_eq!(p.process_chunk(r#"{"name": "now", "#), None);
    assert_eq!(p.tool_calls.len(), 0);
    assert_eq!(p.process_chunk(r#""arguments": {"tz": "UTC"}}"#), None);
    assert_eq!(p.tool_calls.len(), 1);
    assert_eq!(p.tool_calls[0].name, "now");
    assert_eq!(p.tool_calls[0].arguments, serde_json::json!({"tz": "UTC"}));
  }

  #[test]
  fn streaming_inline_leading_text() {
    let mut p = ToolCallProcessor::new(Box::new(InlineJson), None);
    // Text before the first `{` is returned for display.
    let out = p.process_chunk(r#"sure {"name": "now", "arguments": {}}"#);
    assert_eq!(out.as_deref(), Some("sure "));
    assert_eq!(p.tool_calls.len(), 1);
    assert_eq!(p.tool_calls[0].name, "now");
  }

  #[test]
  fn streaming_inline_balanced_non_tool_call_flushed() {
    let mut p = ToolCallProcessor::new(Box::new(InlineJson), None);
    // Balanced JSON that is not a tool call (no `name`): flushed back as text.
    let out = p.process_chunk(r#"{"unrelated": 1}"#);
    assert_eq!(out.as_deref(), Some(r#"{"unrelated": 1}"#));
    assert!(p.tool_calls.is_empty());
  }

  #[test]
  fn streaming_inline_no_brace_passthrough() {
    let mut p = ToolCallProcessor::new(Box::new(InlineJson), None);
    assert_eq!(
      p.process_chunk("just plain text").as_deref(),
      Some("just plain text")
    );
    assert!(p.tool_calls.is_empty());
  }

  // --- end-of-sequence (mistral: start tag, no end tag) --------------------

  #[test]
  fn streaming_mistral_eos() {
    let mut p = ToolCallProcessor::new(Box::new(Mistral), None);
    // Mistral has no end tag in the text stream — the call stays buffered ...
    assert_eq!(
      p.process_chunk(r#"[TOOL_CALLS]get_weather[ARGS]{"city": "Tokyo"}"#),
      None
    );
    assert_eq!(p.tool_calls.len(), 0);
    // ... until process_eos parses the buffered tail.
    p.process_eos();
    assert_eq!(p.tool_calls.len(), 1);
    assert_eq!(p.tool_calls[0].name, "get_weather");
    assert_eq!(
      p.tool_calls[0].arguments,
      serde_json::json!({"city": "Tokyo"})
    );
  }

  #[test]
  fn streaming_eos_noop_when_normal() {
    let mut p = ToolCallProcessor::new(Box::new(JsonTools), None);
    p.process_chunk("plain text");
    // EOS while in Normal state with an empty buffer extracts nothing.
    p.process_eos();
    assert!(p.tool_calls.is_empty());
  }

  // --- malformed / partial input: no panic ---------------------------------

  #[test]
  fn streaming_malformed_partial_no_panic() {
    let mut p = ToolCallProcessor::new(Box::new(JsonTools), None);
    // A start tag with garbage payload that never closes: buffered, no panic,
    // no spurious tool call, and process_eos drops the unparseable tail.
    assert_eq!(p.process_chunk("<tool_call>{not valid json"), None);
    assert!(p.tool_calls.is_empty());
    p.process_eos();
    assert!(p.tool_calls.is_empty());
  }

  #[test]
  fn streaming_malformed_unicode_chunks_no_panic() {
    let mut p = ToolCallProcessor::new(Box::new(JsonTools), None);
    // Non-ASCII text around a partial tag must not slice a UTF-8 boundary.
    let _ = p.process_chunk("héllo <");
    let _ = p.process_chunk("tøøl");
    let _ = p.process_chunk("</tool_call>");
    p.process_eos();
    // No assertion on contents — the contract here is "does not panic".
  }

  #[test]
  fn streaming_malformed_inline_garbage_no_panic() {
    let mut p = ToolCallProcessor::new(Box::new(InlineJson), None);
    // Unbalanced inline braces with garbage: buffered without panic.
    assert_eq!(p.process_chunk("{{{ broken"), None);
    assert!(p.tool_calls.is_empty());
    p.process_eos();
    assert!(p.tool_calls.is_empty());
  }

  // --- adversarial: Codex findings 1-4 -------------------------------------

  #[test]
  fn streaming_inline_object_then_suffix_one_chunk() {
    // Codex finding 1: an inline JSON object immediately followed by display
    // text in the SAME chunk. Extraction must not depend on the chunk ending
    // exactly at the closing brace: the object is parsed as the tool call and
    // the suffix is returned as display text.
    let mut p = ToolCallProcessor::new(Box::new(InlineJson), None);
    let out = p.process_chunk(r#"{"name":"now","arguments":{}} done"#);
    assert_eq!(out.as_deref(), Some(" done"));
    assert_eq!(p.tool_calls.len(), 1);
    assert_eq!(p.tool_calls[0].name, "now");
    // And the same bytes split right after the brace behave identically.
    let mut p2 = ToolCallProcessor::new(Box::new(InlineJson), None);
    assert_eq!(p2.process_chunk(r#"{"name":"now","arguments":{}}"#), None);
    assert_eq!(p2.process_chunk(" done").as_deref(), Some(" done"));
    assert_eq!(p2.tool_calls.len(), 1);
    assert_eq!(p2.tool_calls[0].name, "now");
  }

  #[test]
  fn streaming_inline_suffix_is_a_second_tool_call() {
    // Codex finding 1 (continued): when the suffix after a balanced object is
    // itself another object, it is extracted as a subsequent tool call rather
    // than leaked as text — all in one chunk.
    let mut p = ToolCallProcessor::new(Box::new(InlineJson), None);
    let out = p.process_chunk(r#"{"name":"a","arguments":{}}{"name":"b","arguments":{}}"#);
    assert_eq!(out, None);
    assert_eq!(p.tool_calls.len(), 2);
    assert_eq!(p.tool_calls[0].name, "a");
    assert_eq!(p.tool_calls[1].name, "b");
  }

  #[test]
  fn streaming_inline_braces_inside_string_value() {
    // Codex finding 3: braces inside a JSON string value must not be counted
    // by the balance scan. `{"unrelated":"}"}` is ONE balanced object, not a
    // truncated `{"unrelated":"}` plus stray `"}`. It has no `name`, so the
    // flush-on-balanced-but-unparseable path returns it verbatim as text.
    let mut p = ToolCallProcessor::new(Box::new(InlineJson), None);
    let out = p.process_chunk(r#"{"unrelated":"}"}"#);
    assert_eq!(out.as_deref(), Some(r#"{"unrelated":"}"}"#));
    assert!(p.tool_calls.is_empty());
    // The same braces-in-string inside a real tool call still parse.
    let mut p2 = ToolCallProcessor::new(Box::new(InlineJson), None);
    let out2 = p2.process_chunk(r#"{"name":"echo","arguments":{"s":"a}b{c"}}"#);
    assert_eq!(out2, None);
    assert_eq!(p2.tool_calls.len(), 1);
    assert_eq!(p2.tool_calls[0].name, "echo");
    assert_eq!(
      p2.tool_calls[0].arguments,
      serde_json::json!({"s": "a}b{c"})
    );
  }

  #[test]
  fn streaming_inline_unbalanced_stream_is_bounded() {
    // Codex finding 2: an inline JSON object whose braces never balance must
    // not let the buffer grow without bound. Once past the cap the processor
    // recovers (drops the runaway tool content) instead of OOM-ing/panicking.
    let mut p = ToolCallProcessor::new(Box::new(InlineJson), None);
    // Open an object and never close it; feed well past the cap in chunks.
    assert_eq!(p.process_chunk(r#"{"name":"now","arguments":{"x":""#), None);
    let big = "a".repeat(64 * 1024);
    // Peak after a post-append cap check: the cap plus the last chunk.
    let bound = MAX_TOOL_CALL_BUFFER_BYTES + big.len();
    let total_fed: usize = 8 * big.len();
    for _ in 0..8 {
      let _ = p.process_chunk(&big);
      // Bounded at every step: it tracks the cap, never the total fed.
      assert!(p.tool_call_buffer.len() <= bound);
    }
    // Far more bytes were fed than the buffer ever held — growth is O(cap),
    // not O(total output).
    assert!(total_fed > bound);
    // The runaway tool content was dropped, never parsed into a tool call.
    assert!(p.tool_calls.is_empty());
    assert_eq!(p.tool_call_buffer.len(), 0);
    // The processor recovers to a working state: a fresh valid call parses.
    let out = p.process_chunk(r#"{"name":"ok","arguments":{}}"#);
    assert_eq!(out, None);
    assert_eq!(p.tool_calls.len(), 1);
    assert_eq!(p.tool_calls[0].name, "ok");
  }

  #[test]
  fn streaming_tagged_missing_end_tag_is_bounded() {
    // Codex finding 2: a tagged tool call whose end tag never arrives must
    // also be bounded. `<tool_call>` is confirmed, then content streams
    // forever with no `</tool_call>`; at the cap the malformed content is
    // dropped and the buffer reset.
    let mut p = ToolCallProcessor::new(Box::new(JsonTools), None);
    assert_eq!(p.process_chunk(r#"<tool_call>{"name":"now""#), None);
    let big = "b".repeat(64 * 1024);
    let bound = MAX_TOOL_CALL_BUFFER_BYTES + big.len();
    for _ in 0..8 {
      let _ = p.process_chunk(&big);
      assert!(p.tool_call_buffer.len() <= bound);
    }
    assert_eq!(p.tool_call_buffer.len(), 0);
    assert!(p.tool_calls.is_empty());
  }

  #[test]
  fn streaming_mistral_empty_end_tag_is_bounded() {
    // Codex finding 2: Mistral's end tag is empty (closed at EOS only). A
    // runaway generation must still be bounded rather than buffering forever.
    let mut p = ToolCallProcessor::new(Box::new(Mistral), None);
    assert_eq!(
      p.process_chunk(r#"[TOOL_CALLS]get_weather[ARGS]{"city":""#),
      None
    );
    let big = "c".repeat(64 * 1024);
    let bound = MAX_TOOL_CALL_BUFFER_BYTES + big.len();
    for _ in 0..8 {
      let _ = p.process_chunk(&big);
      assert!(p.tool_call_buffer.len() <= bound);
    }
    assert_eq!(p.tool_call_buffer.len(), 0);
    // EOS after recovery is a clean no-op (nothing buffered, nothing parsed).
    p.process_eos();
    assert!(p.tool_calls.is_empty());
  }

  #[test]
  fn streaming_many_back_to_back_tagged_calls_no_stack_overflow() {
    // Codex finding 4: a single chunk packed with thousands of back-to-back
    // tagged tool calls. The trailing-text-after-end-tag handling must be an
    // iterative loop, not recursive self-calls — recursion would overflow the
    // stack here. All calls must be extracted, in order.
    const N: usize = 4000;
    let mut chunk = String::with_capacity(N * 56);
    for i in 0..N {
      chunk.push_str(&format!(
        r#"<tool_call>{{"name":"f","arguments":{{"i":{i}}}}}</tool_call>"#
      ));
    }
    // The whole batch stays under the buffer cap, so only finding 4 (not the
    // finding-2 cap) is exercised.
    assert!(chunk.len() <= MAX_TOOL_CALL_BUFFER_BYTES);
    let mut p = ToolCallProcessor::new(Box::new(JsonTools), None);
    let out = p.process_chunk(&chunk);
    assert_eq!(out, None);
    assert_eq!(p.tool_calls.len(), N);
    // Ordering preserved: argument `i` increases monotonically with index.
    for (idx, call) in p.tool_calls.iter().enumerate() {
      assert_eq!(call.name, "f");
      assert_eq!(call.arguments, serde_json::json!({ "i": idx }));
    }
  }

  // --- adversarial: Codex round-2 findings 1-2 -----------------------------

  /// Feed `full` to a fresh `json_tools` processor in the given `chunks`,
  /// returning the concatenated display text and the extracted tool calls.
  /// A `None` from `process_chunk` contributes nothing to the display string.
  fn run_tagged_stream(chunks: &[&str]) -> (String, Vec<ToolCall>) {
    let mut p = ToolCallProcessor::new(Box::new(JsonTools), None);
    let mut display = String::new();
    for c in chunks {
      if let Some(d) = p.process_chunk(c) {
        display.push_str(&d);
      }
    }
    p.process_eos();
    (display, p.tool_calls)
  }

  #[test]
  fn streaming_tagged_leading_text_is_boundary_equivalent() {
    // Codex round-2 finding 1: display text before a *real* start tag must be
    // emitted, and the stream's output must be identical regardless of where
    // chunk boundaries fall. Whole-chunk vs split-immediately-before-the-tag
    // must yield the same display text and the same tool calls.
    let whole = r#"Let me check. <tool_call>{"name":"ls","arguments":{}}</tool_call>"#;
    let (d_whole, calls_whole) = run_tagged_stream(&[whole]);
    let (d_split, calls_split) = run_tagged_stream(&[
      "Let me check. ",
      r#"<tool_call>{"name":"ls","arguments":{}}</tool_call>"#,
    ]);
    // The leading prose is never dropped...
    assert_eq!(d_whole, "Let me check. ");
    // ...and is identical no matter the boundary.
    assert_eq!(d_whole, d_split);
    assert_eq!(calls_whole.len(), 1);
    assert_eq!(calls_split.len(), 1);
    assert_eq!(calls_whole[0].name, "ls");
    assert_eq!(calls_split[0].name, "ls");
    // A boundary in the *middle* of the leading text is equivalent too.
    let (d_mid, calls_mid) = run_tagged_stream(&[
      "Let me ",
      r#"check. <tool_call>{"name":"ls","arguments":{}}</tool_call>"#,
    ]);
    assert_eq!(d_mid, "Let me check. ");
    assert_eq!(calls_mid.len(), 1);
  }

  #[test]
  fn streaming_tagged_display_text_between_two_calls() {
    // Codex round-2 finding 1 (continued): display text *between* two
    // back-to-back tagged calls must also be emitted, both when the whole
    // stream arrives in one chunk and when it is split. The trailing-suffix
    // loop re-enters `Normal` on the second start tag, so the inter-call text
    // is leading text for the second call and must surface.
    let whole = concat!(
      r#"<tool_call>{"name":"a","arguments":{}}</tool_call>"#,
      " and then ",
      r#"<tool_call>{"name":"b","arguments":{}}</tool_call>"#,
    );
    let (d_whole, calls_whole) = run_tagged_stream(&[whole]);
    assert_eq!(d_whole, " and then ");
    assert_eq!(calls_whole.len(), 2);
    assert_eq!(calls_whole[0].name, "a");
    assert_eq!(calls_whole[1].name, "b");
    // Same stream, split at every gap — identical output.
    let (d_split, calls_split) = run_tagged_stream(&[
      r#"<tool_call>{"name":"a","arguments":{}}</tool_call>"#,
      " and then ",
      r#"<tool_call>{"name":"b","arguments":{}}</tool_call>"#,
    ]);
    assert_eq!(d_split, " and then ");
    assert_eq!(calls_split.len(), 2);
    assert_eq!(calls_split[1].name, "b");
  }

  #[test]
  fn streaming_tagged_end_delimiter_inside_json_string_value() {
    // Codex round-2 finding 2: a `json_tools` tagged call whose argument
    // *string value* contains the literal end delimiter `</tool_call>`. A
    // naive `contains` / first-match split would cut the JSON object at the
    // delimiter inside the string, fail to parse, and discard the call (the
    // tail leaking as display text). The JSON-string-aware end-tag scan must
    // find the *real* close after the balanced object, extracting the call
    // intact with the delimiter preserved inside the string.
    let mut p = ToolCallProcessor::new(Box::new(JsonTools), None);
    let out =
      p.process_chunk(r#"<tool_call>{"name":"echo","arguments":{"s":"</tool_call>"}}</tool_call>"#);
    assert_eq!(out, None, "no suffix may leak as display text");
    assert_eq!(p.tool_calls.len(), 1, "the call must not be discarded");
    assert_eq!(p.tool_calls[0].name, "echo");
    assert_eq!(
      p.tool_calls[0].arguments,
      serde_json::json!({"s": "</tool_call>"}),
      "the delimiter inside the string argument is preserved verbatim"
    );
  }

  #[test]
  fn streaming_tagged_end_delimiter_in_string_split_across_chunks() {
    // Finding 2 (continued): the same payload, but the chunk boundary lands
    // *inside* the string value that contains the delimiter. The premature
    // `</tool_call>` inside the still-open object must not end collection;
    // only the real end tag after the balanced object completes the call.
    let mut p = ToolCallProcessor::new(Box::new(JsonTools), None);
    assert_eq!(
      p.process_chunk(r#"<tool_call>{"name":"echo","arguments":{"s":"<"#),
      None
    );
    assert_eq!(p.tool_calls.len(), 0);
    assert_eq!(p.process_chunk(r#"/tool_call>"}}</tool_call>"#), None);
    assert_eq!(p.tool_calls.len(), 1);
    assert_eq!(p.tool_calls[0].name, "echo");
    assert_eq!(
      p.tool_calls[0].arguments,
      serde_json::json!({"s": "</tool_call>"})
    );
  }

  #[test]
  fn streaming_tagged_end_delimiter_in_string_then_trailing_text() {
    // Finding 2 (continued): a delimiter-bearing call followed by genuine
    // display text. The real end tag is located after the balanced object, so
    // the trailing text — and only the trailing text — is emitted.
    let mut p = ToolCallProcessor::new(Box::new(JsonTools), None);
    let out = p.process_chunk(
      r#"<tool_call>{"name":"echo","arguments":{"s":"</tool_call>"}}</tool_call> done"#,
    );
    assert_eq!(out.as_deref(), Some(" done"));
    assert_eq!(p.tool_calls.len(), 1);
    assert_eq!(p.tool_calls[0].name, "echo");
    assert_eq!(
      p.tool_calls[0].arguments,
      serde_json::json!({"s": "</tool_call>"})
    );
  }

  #[test]
  fn find_tagged_end_tag_json_vs_plain() {
    // JSON-payload mode: an end tag inside a string value is skipped; the
    // first end tag after the balanced object is the real one.
    let buf = r#"<tool_call>{"s":"</tool_call>"}</tool_call>"#;
    let pos = find_tagged_end_tag(buf, "<tool_call>", "</tool_call>", true)
      .expect("real end tag after the balanced object");
    assert_eq!(&buf[..pos], r#"<tool_call>{"s":"</tool_call>"}"#);
    assert_eq!(&buf[pos..], "</tool_call>");
    // Plain (non-JSON) mode finds the *first* occurrence — the in-string one.
    let plain = find_tagged_end_tag(buf, "<tool_call>", "</tool_call>", false)
      .expect("first substring match");
    assert!(
      plain < pos,
      "plain detection stops at the in-string delimiter"
    );
    // JSON mode while the object is still open: no end tag is accepted.
    assert_eq!(
      find_tagged_end_tag(
        r#"<tool_call>{"s":"</tool_call>"#,
        "<tool_call>",
        "</tool_call>",
        true,
      ),
      None
    );
  }

  // --- helper unit coverage ------------------------------------------------

  #[test]
  fn balanced_json_object_prefix_basics() {
    // No brace at all -> no object.
    assert_eq!(balanced_json_object_prefix(""), None);
    assert_eq!(balanced_json_object_prefix("plain text"), None);
    // Smallest object, and a nested one.
    assert_eq!(balanced_json_object_prefix("{}"), Some((0, 2)));
    assert_eq!(
      balanced_json_object_prefix(r#"{"a": {"b": 1}}"#),
      Some((0, 15))
    );
    // Still open -> keep buffering.
    assert_eq!(balanced_json_object_prefix("{"), None);
    assert_eq!(balanced_json_object_prefix(r#"{"a": {"b":"#), None);
  }

  #[test]
  fn balanced_json_object_prefix_is_string_aware() {
    // Codex finding 3: braces *inside* a JSON string value must not count.
    // A naive byte counter sees `{ } {` -> unbalanced; the JSON-aware scan
    // sees one balanced object.
    assert_eq!(
      balanced_json_object_prefix(r#"{"unrelated":"}"}"#),
      Some((0, 17))
    );
    // An escaped quote inside the string keeps string state correct, so the
    // brace after it is still inside the string and not counted.
    assert_eq!(
      balanced_json_object_prefix(r#"{"k":"a\"}b"}"#),
      Some((0, 13))
    );
    // A brace-only string body: every brace is inside the string.
    assert_eq!(
      balanced_json_object_prefix(r#"{"x":"{{{{"}"#),
      Some((0, 12))
    );
  }

  #[test]
  fn balanced_json_object_prefix_finds_prefix_and_suffix() {
    // Codex finding 1: a complete object followed by trailing text returns
    // the object span only, so the suffix can be handled separately.
    let s = r#"{"name":"now","arguments":{}} done"#;
    let (start, end) = balanced_json_object_prefix(s).expect("balanced object");
    assert_eq!(start, 0);
    assert_eq!(&s[start..end], r#"{"name":"now","arguments":{}}"#);
    assert_eq!(&s[end..], " done");
    // Leading text before the first `{` is excluded from the object span.
    let s2 = r#"hi {"a":1} bye"#;
    let (start2, end2) = balanced_json_object_prefix(s2).expect("balanced object");
    assert_eq!(&s2[..start2], "hi ");
    assert_eq!(&s2[start2..end2], r#"{"a":1}"#);
  }

  #[test]
  fn partial_match_basics() {
    assert!(partial_match("", "<tool_call>"));
    assert!(partial_match("<tool", "<tool_call>"));
    assert!(partial_match("<tool_call>", "<tool_call>"));
    // A longer buffer matches only if it starts with the full tag.
    assert!(partial_match("<tool_call>extra", "<tool_call>"));
    assert!(!partial_match("<thinking>", "<tool_call>"));
  }

  #[test]
  fn separate_token_leading_and_trailing() {
    // `return_leading == true`: text *before* the separator, buffer keeps the
    // separator onward.
    let mut buf = String::from("abc<tool_call>def");
    let leading = separate_token(&mut buf, '<', true);
    assert_eq!(leading.as_deref(), Some("abc"));
    assert_eq!(buf, "<tool_call>def");

    // `return_leading == false`: text *after* the separator, buffer keeps up
    // to and including the separator.
    let mut buf = String::from("abc<def");
    let trailing = separate_token(&mut buf, '<', false);
    assert_eq!(trailing.as_deref(), Some("def"));
    assert_eq!(buf, "abc<");

    // Absent separator leaves the buffer untouched.
    let mut buf = String::from("no sep here");
    assert_eq!(separate_token(&mut buf, '<', true), None);
    assert_eq!(buf, "no sep here");
  }

  #[test]
  fn strip_markers_tagged_and_inline() {
    // Tagged: both delimiters removed, inner trimmed.
    let inner = strip_markers(&JsonTools, "<tool_call>  {\"x\": 1}  </tool_call>");
    assert_eq!(inner, r#"{"x": 1}"#);
    // Inline parser (empty markers): only trimmed.
    let inner = strip_markers(&InlineJson, "  {\"x\": 1}  ");
    assert_eq!(inner, r#"{"x": 1}"#);
  }
}
